conflict.settings:
  type: config_object
  label: 'Conflict settings'
  mapping:
    resolution_type:
      type: sequence
      label: 'Resolution Type'
      sequence:
        type: sequence
        label: 'Entity type'
        sequence:
            type: string
            label: 'Bundle'
